apiVersion: v1
kind: Service
metadata:
  name: amwelltest
spec:
  selector:
    name: amwelltest
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: iliav/amwell_test_hub
  labels:
    name: iliav/amwell_test_hub
spec:
  containers:
  - image: iliav/amwell_test_hub
    name: amwelltest
---
